version: '3.8'

services:
  clog:
    container_name: clog
    image: gcd:clog-1.0.6
    restart: always
    ports:
      - "8087:8087"
      - "8077:8077"
    networks:
      - gcd-net
    env_file: local.env

networks:
  gcd-net:
    external: true
