name: clog
description: Centralize log
version: 1.0.9
homepage: https://github.com/andypangaribuan/clog
publish_to: none

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  args: ^2.0.0
  grpc: ^3.1.0
  protobuf: ^2.1.0
  
  fdation: ^1.0.7
  # fdation:
  #   path: /Users/apangaribuan/repo/github/fdation
  
  fdark: ^1.0.6
  # fdark:
  #   path: /Users/apangaribuan/repo/github/fdark

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
  hotreloader: ^3.0.5
