version: "3.8"
name: clog-pro

networks:
  clog-net:
    name: clog-net

services:
  clog-db:
    container_name: clog-db
    image: ghcr.io/hydradatabase/hydra:14-fdbc04dca1e8aab67308193a717e2ed2fd2a061e
    restart: always
    networks:
      - clog-net
    ports:
      - 6677:5432
    environment:
      POSTGRES_USER: cloguser
      POSTGRES_PASSWORD: clogpassword
      POSTGRES_DB: clogdb
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'

