name: clog-pro


networks:
  clog-net:
    name: clog-net


x-general: &general
  restart: always
  security_opt:
    - no-new-privileges:true
  networks:
    - clog-net
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: 3


services:
  clog-qdb:
    container_name: clog-qdb
    image: questdb/questdb:8.2.1
    <<: *general
    privileged: true
    ports:
      - 15300:9000 # web console
      - 15301:8812 # postgres wire protocol
    env_file: clog-qdb.env
    volumes:
      - ./volumes/clog-qdb:/var/lib/questdb


# services:
  # clog-db:
  #   container_name: clog-db
  #   image: ghcr.io/hydradatabase/hydra:14-fdbc04dca1e8aab67308193a717e2ed2fd2a061e
  #   restart: always
  #   networks:
  #     - clog-net
  #   ports:
  #     - 6677:5432
  #   environment:
  #     POSTGRES_USER: cloguser
  #     POSTGRES_PASSWORD: clogpassword
  #     POSTGRES_DB: clogdb
  #   volumes:
  #     - ./postgres/data:/var/lib/postgresql/data
  #     - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
  #   command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'

