[package]
name = "clog"
version = "0.1.0"
edition = "2024"
description = "Centralized gRPC Logging Service for rmod"

[profile.release]
debug = 1
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = "none"

[profile.dev]
opt-level = 0
debug = "full"

[dependencies]
# rmod = { path = "/Users/apangaribuan/ark/repo/gh/rmod" }
rmod = { git = "https://github.com/andypangaribuan/rmod", tag = "v1.0.37" }
async-nats = "0.38"
clickhouse = { version = "0.13", features = ["chrono"] }
futures-util = "0.3"
