ATTACH TABLE _ UUID '80d51610-4609-4788-acf2-680778675989'
(
    `hostname` LowCardinality(String) COMMENT 'Hostname of the server executing the query.',
    `event_date` Date COMMENT 'The date when the event happened.',
    `event_time` DateTime COMMENT 'The date and time when the event happened.',
    `event_time_microseconds` DateTime64(6) COMMENT 'The date and time with microseconds precision when the event happened.',
    `id` UInt64 COMMENT 'ID of processor.',
    `parent_ids` Array(UInt64) COMMENT 'Parent processors IDs.',
    `plan_step` UInt64 COMMENT 'ID of the query plan step which created this processor. The value is zero if the processor was not added from any step.',
    `plan_step_name` String COMMENT 'Name of the query plan step which created this processor. The value is empty if the processor was not added from any step.',
    `plan_step_description` String COMMENT 'Description of the query plan step which created this processor. The value is empty if the processor was not added from any step.',
    `plan_group` UInt64 COMMENT 'Group of the processor if it was created by query plan step. A group is a logical partitioning of processors added from the same query plan step. Group is used only for beautifying the result of EXPLAIN PIPELINE result.',
    `initial_query_id` String COMMENT 'ID of the initial query (for distributed query execution).',
    `query_id` String COMMENT 'ID of the query.',
    `name` LowCardinality(String) COMMENT 'Name of the processor.',
    `elapsed_us` UInt64 COMMENT 'Number of microseconds this processor was executed.',
    `input_wait_elapsed_us` UInt64 COMMENT 'Number of microseconds this processor was waiting for data (from other processor).',
    `output_wait_elapsed_us` UInt64 COMMENT 'Number of microseconds this processor was waiting because output port was full.',
    `input_rows` UInt64 COMMENT 'The number of rows consumed by processor.',
    `input_bytes` UInt64 COMMENT 'The number of bytes consumed by processor.',
    `output_rows` UInt64 COMMENT 'The number of rows generated by processor.',
    `output_bytes` UInt64 COMMENT 'The number of bytes generated by processor.',
    `processor_uniq_id` String COMMENT 'The uniq processor id in pipeline.',
    `step_uniq_id` String COMMENT 'The uniq step id in plan.',
    INDEX event_time_index event_time TYPE minmax GRANULARITY 1,
    INDEX event_time_microseconds_index event_time_microseconds TYPE minmax GRANULARITY 1,
    INDEX query_id_index query_id TYPE bloom_filter(0.001) GRANULARITY 1,
    INDEX initial_query_id_index initial_query_id TYPE bloom_filter(0.001) GRANULARITY 1
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(event_date)
ORDER BY (event_date, event_time)
TTL event_date + toIntervalDay(30)
SETTINGS index_granularity = 8192
COMMENT 'Contains profiling information on processors level (building blocks for a pipeline for query execution.\n\nIt is safe to truncate or drop this table at any time.'
